// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeE86Bn1eNCZ0T_a5yuT16TCPGuP13BgE',
    appId: '1:296331548072:web:e795bac14c31018e07b99d',
    messagingSenderId: '296331548072',
    projectId: 'baitapgiuaki-ecbe0',
    authDomain: 'baitapgiuaki-ecbe0.firebaseapp.com',
    storageBucket: 'baitapgiuaki-ecbe0.firebasestorage.app',
    measurementId: 'G-06QKP214C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tzAgL_EHsTp8L6sr6XcAs9fOjQpMnQI',
    appId: '1:296331548072:android:c6fcc1fb704116e007b99d',
    messagingSenderId: '296331548072',
    projectId: 'baitapgiuaki-ecbe0',
    storageBucket: 'baitapgiuaki-ecbe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5I2XMud_y_q7Qsbu6Pbafgf9R0tl4-0',
    appId: '1:296331548072:ios:9bd62674d94cac9a07b99d',
    messagingSenderId: '296331548072',
    projectId: 'baitapgiuaki-ecbe0',
    storageBucket: 'baitapgiuaki-ecbe0.firebasestorage.app',
    iosBundleId: 'com.example.baitapgiuaky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB5I2XMud_y_q7Qsbu6Pbafgf9R0tl4-0',
    appId: '1:296331548072:ios:9bd62674d94cac9a07b99d',
    messagingSenderId: '296331548072',
    projectId: 'baitapgiuaki-ecbe0',
    storageBucket: 'baitapgiuaki-ecbe0.firebasestorage.app',
    iosBundleId: 'com.example.baitapgiuaky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeE86Bn1eNCZ0T_a5yuT16TCPGuP13BgE',
    appId: '1:296331548072:web:3930c862c0eb364507b99d',
    messagingSenderId: '296331548072',
    projectId: 'baitapgiuaki-ecbe0',
    authDomain: 'baitapgiuaki-ecbe0.firebaseapp.com',
    storageBucket: 'baitapgiuaki-ecbe0.firebasestorage.app',
    measurementId: 'G-04N331XE09',
  );
}
